config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('account/', include('user.urls')),
    path('record/', include('appointment.urls')),
]

if settings.DEBUG:
    urlpatterns += path('debug/', include(debug_toolbar.urls)),
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetDoneView, PasswordChangeDoneView, \
    PasswordResetCompleteView
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.RegisterView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', views.ProfileActivate.as_view(), name='activate'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('password_change/', views.PasswordChangeUserView.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', views.PasswordResetUserView.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmUserView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('<str:username>/', views.ProfileDetail.as_view(), name='profile'),
    path('update/<slug:username>/', views.ProfileUpdateView.as_view(), name='profile_update'),

]

comments/models.py
from django.contrib.auth.models import User
from django.db import models

from homepage.models import Card


class Card_comments(models.Model):
    comment = models.TextField('Отзыв', max_length=50)
    data = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    card = models.ForeignKey(Card, on_delete=models.CASCADE, verbose_name='Врач', related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='User')

    def __str__(self):
        return self.user.username

comments/views.py
from django.shortcuts import render
from django.views import View

from homepage.models import Card


class CommentsDetailViews(View):
    def get(self, request, pk):
        card_comments = Card.objects.get(id=pk)
        return render(request, 'comments/comments.html', {'card_comments': card_comments})


def create_comments(request, pk):
    error = ''
    if request.method == 'POST':
        form = Card_commentsForm(request.POST)

        if form.is_valid():
            form = form.save(commit=False)
            form.card_id = pk
            form.user = request.user
            form.save()
            return redirect('/')
        else:
            error = 'Форма заполнена неверно'

    form = Card_commentsForm()
    context = {'form': form,
               'error': error
               }
    return render(request, 'comments/creat_comments.html', context)

templates/comments/comments.html
{% extends 'homepage/base.html' %}
{% block title %}Отзывы{% endblock %}

{% block content %}
<main>

    <div class="profile">
        <h1>Отзывы</h1>

        {% for el in card_comments.card_comments_set.all %}

            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading"> {{ el.user }} </h4>
                <hr>
                <p> {{ el.comment }} </p>
                <p class="mb-0"> {{ el.data }} </p>
            </div>
        {% endfor %}

    <br>
    <br>
        {%  if card_comments.card_comments_set.count == 0 %}
        <p>Вы можете оставить первый отзыв</p>
    {% endif %}


            <br>

            <button type="button" class="btn btn-primary btn-sm"><a class="p-3 text-white" href="{% url 'creat_comments' card_comments.id %}">
                Добавить отзыв </a></button>

            <button type="button" class="btn btn-secondary btn-sm"><a class="p-3 text-white" href="{% url 'home' %}">
                Назад </a>
            </button>
    <div>
</main>
{% endblock %}

templates/comments/creat_comments.html
{% extends 'homepage/base.html' %}
{% block title %}Отзывы{% endblock %}

{% block content %}

<main>
    <div class="profile">
        <div class="features animate__animated animate__backInDown">
            {% if user.is_authenticated %}
                <h1>Форма по добавлению отзыва </h1>
                <form method="post">
                    {% csrf_token %}

                    <br>
                    {{ form.comment }}

                    <br>
                    <span> {{ error }}</span>
                    <button class="btn btn-success" type="submit"> Сохранить</button>
                    <a href="javascript:history.go(-1)"
                                                                              class="btn btn-secondary btn-sm">Отмена</a>

                </form>
            {% else %}
                <br>
                <br>
                <br>
                <span> Оставлять отзывы могут только авторизованные пользователи</span>
                <a href="{% url 'login' %}">Войти / </a><a href="{% url 'home' %}">На главную</a>
            {% endif %}
            <br>
            <br>
        </div>
</main>

{% endblock %}